// <auto-generated>
// This file was generated by scripts/extract-icons.ts. Do not edit manually.
// </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Diagnostics.CodeAnalysis;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text.Json;
using NgIcons.Core;

namespace NgIcons.CircumIcons;

public static class IconSet
{
    private static readonly Lazy<IReadOnlyDictionary<string, IconDefinition>> IconsLoader = new(() => Load(""));

    public static IReadOnlyList<string> Suffixes { get; } = Array.Empty<string>();

    public static IReadOnlyDictionary<string, IconDefinition> All => IconsLoader.Value;

    public static IconDefinition Get(string name) => All[name];

    public static bool TryGet(string name, [NotNullWhen(true)] out IconDefinition? icon) => All.TryGetValue(name, out icon);

    public static IReadOnlyDictionary<string, IconDefinition> GetBySuffix(string suffix) => Load(suffix);

    private static IReadOnlyDictionary<string, IconDefinition> Load(string suffix)
    {
        try
        {
            var resourceName = string.IsNullOrEmpty(suffix)
                ? $"{typeof(IconSet).Namespace}.Icons.json"
                : $"{typeof(IconSet).Namespace}.Icons-{suffix}.json";
            using var stream = Assembly.GetExecutingAssembly().GetManifestResourceStream(resourceName)
                ?? throw new InvalidOperationException($"Resource '{resourceName}' was not found.");
            using var reader = new StreamReader(stream);
            var json = reader.ReadToEnd();
            var parsed = JsonSerializer.Deserialize<Dictionary<string, string>>(json) ?? new Dictionary<string, string>();
            var dict = new Dictionary<string, IconDefinition>(StringComparer.OrdinalIgnoreCase);
            foreach (var kvp in parsed)
            {
                dict[kvp.Key] = new IconDefinition(kvp.Key, kvp.Value);
            }
            return new ReadOnlyDictionary<string, IconDefinition>(dict);
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine($"[ng-icons] Failed to load icons for {typeof(IconSet).Namespace}: {ex}");
            return new ReadOnlyDictionary<string, IconDefinition>(new Dictionary<string, IconDefinition>(StringComparer.OrdinalIgnoreCase));
        }
    }
}
