// <auto-generated>
// This file was generated by scripts/extract-icons.ts. Do not edit manually.
// </auto-generated>
#nullable enable
using NgIcons.Core;

using System.Reflection;

namespace NgIcons.MaterialSymbols;

/// <summary>
/// Lazy-loading icon set with suffix/variant support.
/// Icons are loaded individually on first access.
/// Memory usage is proportional to the number of icons actually used.
/// Use Instance.Get(), Instance.TryGet(), Instance.PreloadAll() for dynamic access.
/// </summary>
public static class Icons
{
    private static readonly string[] _suffixes = new[] { "outline", "round", "sharp" };

    /// <summary>Icon set instance providing Get, TryGet, PreloadAll, IconNames, Suffixes, and GetIconNames.</summary>
    public static readonly Core.IconSetWithSuffixes Instance = new(Assembly.GetExecutingAssembly(), "NgIcons.MaterialSymbols", "outline", _suffixes);

    public static IconDefinition matOutlinedOutline => Instance.GetOrLoad("matOutlinedOutline");
    public static IconDefinition matRoundedRound => Instance.GetOrLoad("round", "matRoundedRound");
    public static IconDefinition matSharpSharp => Instance.GetOrLoad("sharp", "matSharpSharp");
}
